version: "3.8"

services:
  # Your existing app service
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Your main Dockerfile for the app
    ports:
      - "12345:12345"  # Expose the main app's port
    depends_on:
      - server  # Ensure the app starts after the server
      - mongodb  # Ensure the app starts after MongoDB
    networks:
      - app-network
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017  # Connection string pointing to MongoDB container

  # The server service
  server:
    build:
      context: ./Server  # Path to the Server folder containing Dockerfile.server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"  # Expose the server's port
    networks:
      - app-network

  # MongoDB service
  mongodb:
    image: mongo:latest  # Use the latest MongoDB image
    container_name: mongodb  # Optional, name the container
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
